version: '3.8'

services:
  app1:
    build: ./app
    command: python server1.py

  app2:
    build: ./app
    command: python server2.py

  haproxy:
    image: haproxy:2.8
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
  
  frontend:
    image: nginx:alpine
    ports:
      - "80:80" # Maps localhost:80 to the container's port 80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro # Mounts your frontend folder
    depends_on:
      - haproxy