# pipeline/logstash.conf

input {
    # We will use the 'gelf' (Graylog Extended Format) log driver
    # from Docker. We're telling Logstash to listen on port 12201.
    gelf {
        port => 12201
    }
}

output {
    # Send the processed logs to our Elasticsearch service
    # The 'elasticsearch' host is the service name from docker-compose
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
    }
}